version: '3.8'
services:
  nest-app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - mysql-container
    ports:
      - 3000:3000
    networks:
      - common-network
    environment:
      DATABASE_HOST: mysql-container
      DATABASE_PORT: 3306
      DATABASE_USER: root
      DATABASE_PASSWORD: 12345678
      DATABASE_NAME: golf_club

  mysql-container:
    image: mysql
    volumes:
      - ./mysql-data:/var/lib/mysql # 已修改为相对路径
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: golf_club
      MYSQL_ROOT_PASSWORD: 12345678
    networks:
      - common-network

networks:
  common-network:
    driver: bridge
